version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: kinopoisk
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin"]
      interval: 5s
      timeout: 3s
      retries: 5

  films:
    build: ./films
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql://admin:admin@postgres:5432/kinopoisk"
    ports:
      - "8000:8000"

  auth:
    build: ./auth
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql://admin:admin@postgres:5432/kinopoisk"
    ports:
      - "8001:8001"

#  reviews:
#    build: ./reviews
#    depends_on:
#      postgres:
#        condition: service_healthy
#    environment:
#      DATABASE_URL: "postgresql://admin:admin@postgres:5432/kinopoisk"
#    ports:
#      - "8002:8002"

  users:
    build: ./users
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql://admin:admin@postgres:5432/kinopoisk"
    ports:
      - "8003:8003"

volumes:
  postgres_data:
