version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: kinopoisk
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d kinopoisk"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: on-failure

  films:
    build: ./films
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql://admin:admin@postgres:5432/kinopoisk"
    ports:
      - "8000:8000"
    restart: on-failure

  auth:
    build: ./authorization
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql://admin:admin@postgres:5432/kinopoisk"
    ports:
      - "8001:8001"
    restart: on-failure

  reviews:
    build: ./reviews
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql://admin:admin@postgres:5432/kinopoisk"
    ports:
      - "8002:8002"
    restart: on-failure

  users:
    build: ./users
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql://admin:admin@postgres:5432/kinopoisk"
    ports:
      - "8003:8003"
    restart: on-failure

volumes:
  postgres_data:
